### ISSUE TITLE
Page Title and Subhead Alignment

### ISSUE THREAD

**Issue by hamberguesa** [aymannadeem/yourhaq#28]
The title ("YourHaq") and subhead ("Community driven...") on the home page are left justified, while the title and subhead on the Vision and FAQ pages is centered. Is this intentional or should they all conform to the same text-alignment? Happy to submit a PR fix.

**Comment by dmleong** [comment]
I prefer left justified for all the things

**Comment by aymannadeem** [comment]
💯 to mo' consistency. Another to do after #24.
