### ISSUE TITLE
How to Help section of Home page

### ISSUE THREAD

**Issue by hamberguesa** [aymannadeem/yourhaq#29]
In the How to Help section of the Home page, consider making the icons and subheads (e.g., "Share ideas on issues", etc.) links to the appropriate Github pages to further drive click-throughs/open-source assistance. Happy to submit a PR for this!

**Comment by aymannadeem** [comment]
Agreed, def need a better way to drive engagement/open source input! Let's figure out #24 which should help clarify how to best do this.
