### ISSUE TITLE
Approach to connecting people to legal aid & building record of data?

### ISSUE THREAD

**Issue by hamberguesa** [aymannadeem/yourhaq#35]
@aymannadeem I'm interested to hear your desired approach both for connecting people to legal aid on the site, as well as building a record of discriminatory data. What are the user experiences you envision? Have you checked out [Airport Lawyer](https://www.airportlawyer.org/)? They're doing something similar in terms of connecting people to legal aid. 

As both a lawyer and engineer, I'm super interested in getting involved in supporting projects like this! Thank you for your hard work!

**Comment by littlefoot32** [comment]
![localhostaccountienlogo_meta_black 1](https://cloud.githubusercontent.com/assets/13885641/24233388/eb08267a-0f5f-11e7-9f84-351b92d16c51.gif)

**Comment by littlefoot32** [comment]
![localhostaccountienlogo_meta_black 1](https://cloud.githubusercontent.com/assets/13885641/24233408/12d1eb3c-0f60-11e7-8339-f663808e307a.gif)

**Comment by aymannadeem** [comment]
Thanks for your contributions @hamberguesa — and yeah, seen Airport Lawyer, thanks for the pro tip!
